---
title: Live to learn and learn to live.
author: CalaraZeta
email: support@forestry.io
description: "Learning a new language its not an easy process. That will force you
  to be flexible, having the courage, taking the time and to be determined. \nBy living
  in a new country, learning the language will be the best decision you can make.\nWe
  all have to learn a new language  at one point of time.\nEven though a foreign language
  or a native one. Life in general is a learning journey\n.\nWhy learning a language?
  To be able to communicate, to make friends, or to socialize, to be part of the society,
  to find a job etc.\n\nMost of us have already been in a situation like that, where
  we have no other choice than to learn a new language.\n\nDon't put pressure on yourself,
  don't be shy, don't be afraid to make mistakes."
baseurl: "/deutschtreff"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
